CREATE TABLE IF NOT EXISTS public.capturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidato_id TEXT NOT NULL DEFAULT '',
    timestamp TEXT NOT NULL DEFAULT '',
    status_geral TEXT NOT NULL DEFAULT 'corrigido',
    respostas TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT '[]',
    acertos INTEGER NOT NULL DEFAULT 0,
    erros INTEGER NOT NULL DEFAULT 0,
    pontos DOUBLE PRECISION NOT NULL DEFAULT 0,
    caminho_foto TEXT NOT NULL DEFAULT '',
    caminho_anotada TEXT,
    caminho_gabarito TEXT,
    caminho_limiar TEXT,
    foto_hash TEXT
);

CREATE INDEX IF NOT EXISTS idx_capturas_candidato
    ON public.capturas (candidato_id);

CREATE INDEX IF NOT EXISTS idx_capturas_timestamp
    ON public.capturas (timestamp);

CREATE INDEX IF NOT EXISTS idx_capturas_hash
    ON public.capturas (candidato_id, foto_hash);
